README.md

fix: Update README name

---

.github/.reviewdogConfig.yml
Dockerfile.docs
Makefile
README.md
docs_src/faq.md
docs_src/index.md
docs_src/references.md
docs_src/roadmap.md
mkdocs.yml

feat: Adding documentation page

---

README.md

fix: Update readme document link

---

telegraf/Dockerfile
telegraf/Makefile
telegraf/docker-run-influxdb.sh
telegraf/docker-run-telegraf.sh
telegraf/docker-run.sh
telegraf/intel_core_and_igpu_telemetry.json
telegraf/opt/intel-gpu-telegraf/get_intel_gpu_status.sh
telegraf/opt/intel-gpu-telegraf/telegraf.conf

feat: Add telegraf

---

benchmark-scripts/requirements-xpu.txt

fix: xpu python dependency version fix

---

benchmark-scripts/Dockerfile.benchmark
benchmark-scripts/collect_platform_metrics.sh

Simplify the functionality of the benchmark container. The container will now only run the basic system metrics and run indefinitely. The benchmark python refactor will be in control of the duration of the run.

feat: Simplify benchmark container to only run system metrics

---

benchmark-scripts/Makefile
benchmark-scripts/benchmark.py
benchmark-scripts/benchmark_test.py
benchmark-scripts/camera-simulator.sh
benchmark-scripts/results_parser.py
docker/platform/requirements.txt

Prerequisites:
- python environment with Python 3.12.2 (can use [miniconda](https://rsd-intel.slack.com/archives/C02E1TXQS8Z/p1711055235807679?thread_ts=1711050322.426669&cid=C02E1TXQS8Z) and create a [Python 3.12.2 env](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html))
- installed necessary packages listed in requirements.txt
1. Pull the latest changes from this branch and from the retail-use-cases for updated compose files
2. change directories to the `benchmark-script` directory
3.  change directories `cd docker` and run `make build-igt` to build the benchmark docker container
4. change directories back `cd ..`
5. Ensure that the benchmarking script works run something like this
```
python benchmark.py --compose_file …
```

feat: Convert benchmark.sh to python and add unit tests

---

benchmark-scripts/benchmark.py

feat: add docstring comments to the benchmark script

---

benchmark-scripts/requirements.txt
docker/platform/requirements.txt

install the requirements from benchmark-scripts:
`pip install -r requirements.txt`

fix: revert docker platform reqs, add benchmark requirements

---

benchmark-scripts/benchmark.py

1. set up performance tools submodule
2. ensure benchmark container is built using 'make build-benchmark-docker' from performance tools
3. run the following
```
cd benchmark-scripts
python benchmark.py --compose_file ../../use-cases/gst_capi/add_camera-simulator.yml --compose_file ../../use-cases/gst_capi/add_gst_capi_yolov5_ensemble.yml
```

fix: update default path for git submodule

---

benchmark-scripts/download_sample_videos.sh

Pexels changed their URL format for downloads so new URls are required.
close: #53
1. cd benchmark-scripts
2. ./download_sample_videos.sh
3. See script successfully run
4. See all 4 videos in ./sample-media (barcode, coca-cola, vehicle, people_walking)

fix: sample video links

---

docker/xpum/requirements.txt

fix: Dependabot updates

---

benchmark-scripts/format_avc_mp4.sh

- Updates DLStreamer image used to 2024.1.1-dev
- Move the sample videos to another directory
- Run `make download-sample-videos` 
- Check that the videos are 4k@15FPS
-

feat: update dlstreamer image to 2024.1.1-dev-ubuntu22

---

.github/workflows/scorecard.yml

fix: Update scorecard version

---

helm/Makefile
helm/docker-compose.yaml
helm/intel-top/Dockerfile
helm/intel-top/entrypoint.sh
helm/kubernetes/README.md
helm/kubernetes/igt-volume.yaml
helm/kubernetes/platform-volume.yaml
helm/platform/Dockerfile
helm/platform/entrypoint.sh
helm/platform/requirements.txt
helm/xpum/Dockerfile
helm/xpum/entrypoint.sh
helm/xpum/requirements.txt

- Install Minikube, refer to [here](https://minikube.sigs.k8s.io/docs/start/?arch=%2Flinux%2Fx86-64%2Fstable%2Fbinary+download) for installation instructions
- Run `make run-minikube-demo`
- Check kubernetes pods `minikube kubectl get pods`
- Check minikube container filesystem `docker exec -it minikube /bin/bash`
- Check igt files:
- `cd /tmp/hostpath-provisioner/default/igt-claim0`
- `ls` 
- Check platform files:
- `cd /tmp/hostpath-provisioner/default/platform-claim0`
- `ls`

feat: implement minikube and helm deployment

---

benchmark-scripts/download_sample_videos.sh
benchmark-scripts/format_avc_mp4.sh

- Adds video of people smiling for age-classification pipeline

feat: add new source file, update dlstreamer container to 2.0-dev

---

benchmark-scripts/Makefile
benchmark-scripts/benchmark.py
benchmark-scripts/consolidate_multiple_run_of_metrics.py
benchmark-scripts/requirements.txt

…
when i ran the original consolidate python command through make target: `make consolidate` I encountered some errors regarding to some syntax errors and missing packages, so this PR fixes those issues.
- git clone this PR
- run `make consolidate`
-

fix: fix python3 syntax error and added some missing dependency packages for running make consolidate

---

.github/workflows/build.yaml
.github/workflows/trivy-scan.yaml
.github/workflows/trivyimagescan.yaml

- Updates GitHub Actions to improve runs

feat: update github actions

---

.github/release.yml

add config file for release notes

feat: Add configuration file for release notes

---

docker/platform/entrypoint.sh

1. make PCM it's own process 
2. while loop added at the end of the entrypoint.sh to continue running even if one of the metric tools fails.
close: #**63**
1. cd docker
2. make build-platform
3. make run-platform
4. docker ps -a -> confirm benchmark:platform container is running
5. check /docker/results directory for logs. Ex. CPU log should continue to write results while the container is running
6. docker rm -f platform -> will stop and remove the platform docker container after testing

Fix:Make pcm seperate process and add while loop

---

benchmark-scripts/benchmark_test.py
benchmark-scripts/consolidate_multiple_run_of_metrics.py
benchmark-scripts/requirements.txt

fix: changes to support python 3.12

---

benchmark-scripts/format_avc_mp4.sh

Update DLstreamer docker image

---

docker/xpum/requirements.txt

fix: gunicorn version for security

---

helm/xpum/requirements.txt

fix: gunicorn version for security helm

---

.github/workflows/scorecard.yml

fix: hash for actions/checkout@v4

---

.github/workflows/reports.yaml
.github/workflows/reviewdog.yaml
.github/workflows/scorecard.yml

fix: adding more hashes

---

README.md

add: openssf best practices badge

add: openssf best practices badge

---

benchmark-scripts/benchmark.py
benchmark-scripts/consolidate_multiple_run_of_metrics.py

fix: Small fixes

---

benchmark-scripts/consolidate_multiple_run_of_metrics.py

Following GPU metrics are collected and consolidated in benchmarking:
'CCS %': 'Compute[CCS] Utilization %',
'RCS %': 'Render/3D[RCS] Utilization %',
'VCS %': 'Video[VCS] Utilization %',
'VECS %': 'VideoEnhance[VECS] Utilization %',
'Power W pkg': 'GPU Power (W)',
'RC6 %': 'GPU Idle Time (RC6 %)'

GPU metrics collection and consolidation

---

.github/workflows/build.yaml
.github/workflows/trivyimagescan.yaml

workflow fixes

---

benchmark-scripts/download_sample_videos.sh
benchmark-scripts/format_avc_mp4.sh

GHI-144: Changes to update DLStreamer image and optimization

---

benchmark-scripts/stream_density.py

improved the file search, now one can append after the conntainer name

---

benchmark-scripts/benchmark.py
benchmark-scripts/stream_density.py

Log cleanup
